### ISSUE TITLE
Support for Unicode aliases?

### ISSUE THREAD

**Issue by jeffswt** [xmcp/xmpaint#1]
Or is that `graphviz` does not support Unicode...

Happened to run into issues while writing stuff for bzoj1143.

You can't type Chinese into the *Alias* tab. It will just throw a bunch of nonsense at you after render.

**Comment by xmcp** [comment]
纯ascii的文字用consolas之类的英文字体，包含至少一个非ascii字符的label用中文字体（黑体之类的）。

你觉得这种做法怎么样？

@dramforever

**Comment by dramforever** [comment]
Inziu Iosevka

**Comment by dramforever** [comment]
等下，不能让用户选字体么

**Comment by xmcp** [comment]
@dramforever 
- xmpaint不希望内置字体
- xmpaint不希望再增加一个设置页面（毕竟没什么人拿xmpaint画中文）

so，还能怎么办？

**Comment by xmcp** [comment]
ps. graphviz一个比较显著的坑是（据我所知）fontname不支持fallback
