### ISSUE TITLE
xmpaint是否有linux版？

### ISSUE THREAD

**Issue by WAAutoMaton** [xmcp/xmpaint#3]
RT。
如果没有的话，能否在wine中运行呢？

**Comment by jeffswt** [comment]
你可以在[这里](https://graphviz.gitlab.io/download/)下载适用于 Linux 的 GraphViz；

由于 xmpaint 的开发人员主要使用 Windows，所以不提供 Linux 版的 port。
程序是可以移植到 Linux 上的，改动部分主要位于 `_youhua_compiler.py` 中。
另外部分地方还有只适用于 Windows 的魔改，所以可能移植难度略大。

在 Wine 下应该是可以运行的，但是我们并不建议这样做。
由于本项目维护者 @xmcp 已经退坑，故该项目可能不再更新。

**欢迎各种 Pull Requests；**

**Comment by xmcp** [comment]
没有。（其实你把代码里那些 `.exe` 删掉，然后下个 Linux 版 graphviz 应该就可以有了。）
可以在 Wine 中运行。
